# Generated by Django 2.2.7 on 2019-11-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julkalender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='contributor',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='door',
            unique_together={('year', 'day')},
        ),
    ]
