# Generated by Django 2.2.7 on 2019-11-10 11:58

from django.db import migrations, models
import julkalender.models


class Migration(migrations.Migration):

    dependencies = [
        ('julkalender', '0002_auto_20191110_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='embed_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='door',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='door',
            name='image',
            field=models.FileField(null=True, upload_to=julkalender.models.update_filename),
        ),
    ]
