# Generated by Django 2.2.7 on 2019-11-10 12:11

from django.db import migrations, models
import julkalender.models


class Migration(migrations.Migration):

    dependencies = [
        ('julkalender', '0003_auto_20191110_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=julkalender.models.update_filename),
        ),
    ]
