services:
  web:
    container_name: D-Sektionen-Julkalender
    image: registry.d-sektionen.se/julkalender:latest
    restart: unless-stopped
    entrypoint: /code/docker-entrypoint.sh
    command: uwsgi --ini /code/julkalender.uwsgi.ini
    volumes:
      # Set the paths when deploying to production.
      - ${JULKALENDER_BASEDIR}/julkalender.uwsgi.ini:/etc/uwsgi/julkalender.uwsgi.ini
      - ${JULKALENDER_BASEDIR}/static:/code/static
      - ${JULKALENDER_BASEDIR}/media:/code/media
      - ${JULKALENDER_BASEDIR}/log:/var/log/
      - ${JULKALENDER_BASEDIR}/backup:/backup
    ports:
      - 8002:8000
    environment:
      # Set these when deploying to production
      POSTGRES_NAME: julkalender
      POSTGRES_USER: julkalender
      POSTGRES_PASSWORD: "Y7FNb2c7UmT9g89k6mad52ZGFQ"
      POSTGRES_HOST: 172.17.0.1
      POSTGRES_PORT: 5432
      DJANGO_SETTINGS_MODULE: app.settings_production
    env_file:
      # Environment variables set in portainer gui.
      - stack.env
    networks:
      - default

networks:
  default:
    driver: bridge